language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: Y297BuGQKHvfKkq0MH7jsEmOaIbV40vywjoGJUqN+HVNQlRQOVqDblTqQVBFMgIXXBDBwlqyQ8vpTpzQz+EJjL2klzZSx8Mlu9BWcvnPeCzUnnH6Vt+63c55Do4gnqbprsN19LjM7NkInnvaneldIUYv6zP/uuIrQ4STOU7ytwnd8Zbv3JiIrlzrHT7RtudS2fzElnRYWUbTzgCHseTtG2qx+zU9wCGDoTKFsxzRHq6bz5X249AuyKoXGNg2M64yjskmi42/l26o+AYBttBrFhoKDreKotdP90FM0Bg8amg1ITGgJ07ZJy4Cgna8jCYb+GxrocobUiJPU6RY2GyVotcTPSbf6cZySpI+uClOwNB+wMFYO7if3i8HlZLY3f0rFvc85XNsvZBE4ELcvyr7jlx+u71moJixGI2yAn1H+N6Vkwxy+6OUpaLtGhuvgIyTbuTr9LO7c8GMLxM7ILsnUv0tzCpYyoXNy3Np882RMvxreLZhCsHhiNtWCm8HVZ/E4DdFFjABqibR+zLms0Unco//vu/nUAT+85gS6MwWWpeMywl1G+MEgTY5xatR/Z8tBbp+dH/TfX7NEOpL/5yJB6sM3Nye8ysuTwlO2+X/cGK4g33dTJUWK2hT+5SBO8tgJ70vQVdy8WDtbW4m84/7wTiYRbywboMU+LmmK4zg9RY=
  on:
    tags: true
    repo: gpp-rnd/sglearn
    python: 3.8
